### ISSUE TITLE
Errors occurred while running py

### ISSUE THREAD

**Issue by ProJeKTRED** [UTD-TIES-LAB/RTL-Contest#1]
I copied the core folder of the CVA6 project and tried to detect an error
here is the cva6 project link：https://github.com/openhwgroup/cva6
But there was an error running the module
![image](https://github.com/UTD-TIES-LAB/RTL-Contest/assets/61411788/be9853f1-da30-45f9-a62f-20600fa3c11d)
Should I manually add. v/. sv files to the RTLVerilog folder for detection？
and  why did it also extract some other files, such as. svh, .vlt, and .svg.

I am a beginner in testing, thank you.

**Comment by 90ICEDA** [comment]
> 我复制了 CVA6 项目的核心文件夹并试图检测错误，这里是 cva6 项目链接：https://github.com/openhwgroup/cva6 但是运行模块![image](https://private-user-images.githubusercontent.com/61411788/331775756-be9853f1-da30-45f9-a62f-20600fa3c11d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzkyODIsIm5iZiI6MTcxNjc3ODk4MiwicGF0aCI6Ii82MTQxMTc4OC8zMzE3NzU3NTYtYmU5ODUzZjEtZGEzMC00NWY5LWE2MmYtMjA2MDBmYTNjMTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyY2QwNmE3YjY0NTE4NTNlZmIwMmFkNWRkYjZlNDYzZjBlODA2MTIyNjRkMGQxNzBhZmIyODk4ZGJkOWRhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R8L4lvIbDPFMm0ldC_eJ26zXtj9yL7Au-rOuPrcGS5U)时出错 我应该手动添加吗？sv 文件复制到 RTLVerilog 文件夹进行检测？ 为什么它还提取了一些其他文件，例如。svh、.vlt 和 .svg。
> 
> 我是测试的初学者，谢谢。

I also have this problem.
